apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: httpserver
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: httpserver-cm
      terminationGracePeriodSeconds: 30 
      containers:
        - image: hellochenpro7799/httpserver:v1.1-metrics
          imagePullPolicy: Always
          name: httpserver
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /app/config/
          